searchById=SELECT * FROM MEMBER WHERE USERID=?
insertMember=INSERT INTO MEMBER VALUES(?,?,?,?,?,?,?,?,?,DEFAULT)
updateMember=UPDATE MEMBER SET USERNAME=?, GENGER=?, AGE=?, EMAIL=?, PHONE=?, ADDRESS=?, HOBBY=? WHERE USERID=?
