searchNoticeAll=SELECT * FROM \
					(SELECT ROWNUM AS RNUM, N.* FROM \
							(SELECT * FROM NOTICE ORDER BY NOTICE_NO DESC)N) \
				WHERE RNUM BETWEEN ? AND ?
noticeCount=SELECT COUNT(*) as cnt FROM NOTICE
insertNotice=INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL,?,?,?,DEFAULT,?,DEFAULT)
searchNoticeByNo=SELECT * FROM NOTICE WHERE NOTICE_NO=?